#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : RBM_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Aug 28 06:23:11 PDT 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: RBM_bd.sh [-help]
# usage: RBM_bd.sh [-lib_map_path]
# usage: RBM_bd.sh [-noclean_files]
# usage: RBM_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'RBM_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_18 floating_point_v7_1_15 axi_infrastructure_v1_1_0 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 lib_pkg_v1_0_2 fifo_generator_v13_2_7 lib_fifo_v1_0_16 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_29 axi_sg_v4_1_15 axi_dma_v7_1_28 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_27 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 axi_protocol_converter_v2_1_27 axi_clock_converter_v2_1_26 blk_mem_gen_v8_4_5 axi_dwidth_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "RBM_bd.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_control_split.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_data_flow_control.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_double_buffer.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w8_d128_S.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w10_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w12_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w21_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w21_d1024_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w21_d1024_A_x.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w48_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w49_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w64_d128_A.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w640_d128_D.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_fifo_w1600_d128_D.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_hls_deadlock_detection_unit.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_mul_55s_24ns_79_2_1.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_mul_mul_25s_16s_41_4_1.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_mux_646_1_1_1.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_rbm_size_split.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_regslice_both.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_sigmoid.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_sigmoid_sigmoid_bias_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_sigmoid_sigmoid_slope_V_ROM_AUTO_1R.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_start_for_data_flow_control_U0.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_start_for_double_buffer_U0.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_start_for_sigmoid_U0.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_start_for_systolic_array_U0.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_start_for_weight_bias_memory_U0.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_systolic_array.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_weight_bias_memory.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_weight_bias_memory_bias_V_RAM_AUTO_1R1W.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM_weight_bias_memory_weight_bias_memory_stream_stream_stream_stream_stream_strebkb.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog/RBM.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_RBM_0_0/sim/RBM_bd_RBM_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_18 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_15 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/22f8/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work floating_point_v7_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/22f8/hdl/floating_point_v7_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog/RBM_interface_fpext_32ns_64_2_no_dsp_1.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog/RBM_interface_hls_deadlock_idx0_monitor.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog/RBM_interface_regslice_both.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog/RBM_interface.v" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/ip/RBM_interface_fpext_32ns_64_2_no_dsp_1_ip.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_RBM_interface_0_0/sim/RBM_bd_RBM_interface_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_processing_system7_0_0/sim/RBM_bd_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_rst_ps7_0_50M_0/sim/RBM_bd_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_29 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/2237/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/751a/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_28 $vhdlan_opts \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/70c4/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_0/sim/RBM_bd_axi_dma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_xbar_0/sim/RBM_bd_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_1_0/sim/RBM_bd_axi_dma_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_xbar_1/sim/RBM_bd_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_2_0/sim/RBM_bd_axi_dma_2_0.vhd" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_3_0/sim/RBM_bd_axi_dma_3_0.vhd" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_4_0/sim/RBM_bd_axi_dma_4_0.vhd" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_5_0/sim/RBM_bd_axi_dma_5_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_xbar_2/sim/RBM_bd_xbar_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_axi_dma_6_0/sim/RBM_bd_axi_dma_6_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_xbar_3/sim/RBM_bd_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b8be/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/25a8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/4675/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/fd9f/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/b723/hdl/verilog" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../RBM_vivado.gen/sources_1/bd/RBM_bd/ipshared/ee60/hdl" +incdir+"/home/ubuntu20/Softwares/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_auto_us_0/sim/RBM_bd_auto_us_0.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_auto_pc_0/sim/RBM_bd_auto_pc_0.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_auto_pc_1/sim/RBM_bd_auto_pc_1.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_auto_pc_2/sim/RBM_bd_auto_pc_2.v" \
    "$ref_dir/../../../bd/RBM_bd/ip/RBM_bd_auto_pc_3/sim/RBM_bd_auto_pc_3.v" \
    "$ref_dir/../../../bd/RBM_bd/sim/RBM_bd.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.RBM_bd xil_defaultlib.glbl -o RBM_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./RBM_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./RBM_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ubuntu20/Xilinx/ELE548/Restricted_Boltzmann_Machine/RBM_vivado/RBM_vivado.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key RBM_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc RBM_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./RBM_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: RBM_bd.sh [-help]\n\
Usage: RBM_bd.sh [-lib_map_path]\n\
Usage: RBM_bd.sh [-reset_run]\n\
Usage: RBM_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
