-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity RBM_rbm_size_split is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    vector_in_len_TVALID : IN STD_LOGIC;
    vector_out_len_TVALID : IN STD_LOGIC;
    vector_in_len_ch176_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_in_len_ch176_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch176_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch176_full_n : IN STD_LOGIC;
    vector_in_len_ch176_write : OUT STD_LOGIC;
    vector_in_len_ch277_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_in_len_ch277_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch277_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch277_full_n : IN STD_LOGIC;
    vector_in_len_ch277_write : OUT STD_LOGIC;
    vector_in_len_ch378_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_in_len_ch378_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch378_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_in_len_ch378_full_n : IN STD_LOGIC;
    vector_in_len_ch378_write : OUT STD_LOGIC;
    vector_out_len_ch179_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_out_len_ch179_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch179_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch179_full_n : IN STD_LOGIC;
    vector_out_len_ch179_write : OUT STD_LOGIC;
    vector_out_len_ch280_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_out_len_ch280_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch280_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch280_full_n : IN STD_LOGIC;
    vector_out_len_ch280_write : OUT STD_LOGIC;
    vector_out_len_ch381_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    vector_out_len_ch381_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch381_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    vector_out_len_ch381_full_n : IN STD_LOGIC;
    vector_out_len_ch381_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    vector_in_len_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    vector_in_len_TREADY : OUT STD_LOGIC;
    vector_out_len_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    vector_out_len_TREADY : OUT STD_LOGIC );
end;


architecture behav of RBM_rbm_size_split is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal tmp_nbreadreq_fu_42_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_nbreadreq_fu_56_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_reg_120 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_131 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal vector_in_len_TDATA_blk_n : STD_LOGIC;
    signal vector_out_len_TDATA_blk_n : STD_LOGIC;
    signal vector_in_len_ch176_blk_n : STD_LOGIC;
    signal vector_in_len_ch277_blk_n : STD_LOGIC;
    signal vector_in_len_ch378_blk_n : STD_LOGIC;
    signal vector_out_len_ch179_blk_n : STD_LOGIC;
    signal vector_out_len_ch280_blk_n : STD_LOGIC;
    signal vector_out_len_ch381_blk_n : STD_LOGIC;
    signal vector_in_length_fu_112_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal vector_in_length_reg_124 : STD_LOGIC_VECTOR (11 downto 0);
    signal vector_out_length_fu_116_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal vector_out_length_reg_135 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal regslice_both_vector_in_len_U_apdone_blk : STD_LOGIC;
    signal vector_in_len_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal vector_in_len_TVALID_int_regslice : STD_LOGIC;
    signal vector_in_len_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vector_in_len_U_ack_in : STD_LOGIC;
    signal regslice_both_vector_out_len_U_apdone_blk : STD_LOGIC;
    signal vector_out_len_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal vector_out_len_TVALID_int_regslice : STD_LOGIC;
    signal vector_out_len_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vector_out_len_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component RBM_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_vector_in_len_U : component RBM_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vector_in_len_TDATA,
        vld_in => vector_in_len_TVALID,
        ack_in => regslice_both_vector_in_len_U_ack_in,
        data_out => vector_in_len_TDATA_int_regslice,
        vld_out => vector_in_len_TVALID_int_regslice,
        ack_out => vector_in_len_TREADY_int_regslice,
        apdone_blk => regslice_both_vector_in_len_U_apdone_blk);

    regslice_both_vector_out_len_U : component RBM_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => vector_out_len_TDATA,
        vld_in => vector_out_len_TVALID,
        ack_in => regslice_both_vector_out_len_U_ack_in,
        data_out => vector_out_len_TDATA_int_regslice,
        vld_out => vector_out_len_TVALID_int_regslice,
        ack_out => vector_out_len_TREADY_int_regslice,
        apdone_blk => regslice_both_vector_out_len_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                tmp_reg_120 <= tmp_nbreadreq_fu_42_p3;
                tmp_s_reg_131 <= tmp_s_nbreadreq_fu_56_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                vector_in_length_reg_124 <= vector_in_length_fu_112_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                vector_out_length_reg_135 <= vector_out_length_fu_116_p1;
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (real_start, ap_CS_iter0_fsm, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (real_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)))) and not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0))))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(real_start, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)))) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n)
    begin
        if ((((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(real_start, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    internal_ap_ready_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_nbreadreq_fu_42_p3 <= (0=>(vector_in_len_TVALID_int_regslice), others=>'-');
    tmp_s_nbreadreq_fu_56_p3 <= (0=>(vector_out_len_TVALID_int_regslice), others=>'-');

    vector_in_len_TDATA_blk_n_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, tmp_nbreadreq_fu_42_p3, ap_done_reg, vector_in_len_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_1))) then 
            vector_in_len_TDATA_blk_n <= vector_in_len_TVALID_int_regslice;
        else 
            vector_in_len_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_in_len_TREADY <= regslice_both_vector_in_len_U_ack_in;

    vector_in_len_TREADY_int_regslice_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            vector_in_len_TREADY_int_regslice <= ap_const_logic_1;
        else 
            vector_in_len_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    vector_in_len_ch176_blk_n_assign_proc : process(vector_in_len_ch176_full_n, tmp_reg_120, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch176_blk_n <= vector_in_len_ch176_full_n;
        else 
            vector_in_len_ch176_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_in_len_ch176_din <= vector_in_length_reg_124;

    vector_in_len_ch176_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch176_write <= ap_const_logic_1;
        else 
            vector_in_len_ch176_write <= ap_const_logic_0;
        end if; 
    end process;


    vector_in_len_ch277_blk_n_assign_proc : process(tmp_reg_120, vector_in_len_ch277_full_n, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch277_blk_n <= vector_in_len_ch277_full_n;
        else 
            vector_in_len_ch277_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_in_len_ch277_din <= vector_in_length_reg_124;

    vector_in_len_ch277_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch277_write <= ap_const_logic_1;
        else 
            vector_in_len_ch277_write <= ap_const_logic_0;
        end if; 
    end process;


    vector_in_len_ch378_blk_n_assign_proc : process(tmp_reg_120, vector_in_len_ch378_full_n, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch378_blk_n <= vector_in_len_ch378_full_n;
        else 
            vector_in_len_ch378_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_in_len_ch378_din <= vector_in_length_reg_124;

    vector_in_len_ch378_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_reg_120 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_in_len_ch378_write <= ap_const_logic_1;
        else 
            vector_in_len_ch378_write <= ap_const_logic_0;
        end if; 
    end process;

    vector_in_length_fu_112_p1 <= vector_in_len_TDATA_int_regslice(12 - 1 downto 0);

    vector_out_len_TDATA_blk_n_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_out_len_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (real_start = ap_const_logic_1))) then 
            vector_out_len_TDATA_blk_n <= vector_out_len_TVALID_int_regslice;
        else 
            vector_out_len_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_out_len_TREADY <= regslice_both_vector_out_len_U_ack_in;

    vector_out_len_TREADY_int_regslice_assign_proc : process(real_start, ap_CS_iter0_fsm_state1, tmp_nbreadreq_fu_42_p3, tmp_s_nbreadreq_fu_56_p3, ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2, vector_in_len_TVALID_int_regslice, vector_out_len_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0) or ((tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (vector_out_len_TVALID_int_regslice = ap_const_logic_0)) or ((tmp_nbreadreq_fu_42_p3 = ap_const_lv1_1) and (vector_in_len_TVALID_int_regslice = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))))) and (tmp_s_nbreadreq_fu_56_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            vector_out_len_TREADY_int_regslice <= ap_const_logic_1;
        else 
            vector_out_len_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    vector_out_len_ch179_blk_n_assign_proc : process(vector_out_len_ch179_full_n, tmp_s_reg_131, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch179_blk_n <= vector_out_len_ch179_full_n;
        else 
            vector_out_len_ch179_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_out_len_ch179_din <= vector_out_length_reg_135;

    vector_out_len_ch179_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch179_write <= ap_const_logic_1;
        else 
            vector_out_len_ch179_write <= ap_const_logic_0;
        end if; 
    end process;


    vector_out_len_ch280_blk_n_assign_proc : process(tmp_s_reg_131, vector_out_len_ch280_full_n, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch280_blk_n <= vector_out_len_ch280_full_n;
        else 
            vector_out_len_ch280_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_out_len_ch280_din <= vector_out_length_reg_135;

    vector_out_len_ch280_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch280_write <= ap_const_logic_1;
        else 
            vector_out_len_ch280_write <= ap_const_logic_0;
        end if; 
    end process;


    vector_out_len_ch381_blk_n_assign_proc : process(tmp_s_reg_131, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if (((tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch381_blk_n <= vector_out_len_ch381_full_n;
        else 
            vector_out_len_ch381_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vector_out_len_ch381_din <= vector_out_length_reg_135;

    vector_out_len_ch381_write_assign_proc : process(ap_done_reg, vector_in_len_ch176_full_n, tmp_reg_120, vector_in_len_ch277_full_n, vector_in_len_ch378_full_n, vector_out_len_ch179_full_n, tmp_s_reg_131, vector_out_len_ch280_full_n, vector_out_len_ch381_full_n, ap_CS_iter1_fsm_state2)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch179_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch381_full_n = ap_const_logic_0)) or ((tmp_s_reg_131 = ap_const_lv1_1) and (vector_out_len_ch280_full_n = ap_const_logic_0)) or ((vector_in_len_ch378_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((vector_in_len_ch277_full_n = ap_const_logic_0) and (tmp_reg_120 = ap_const_lv1_1)) or ((tmp_reg_120 = ap_const_lv1_1) and (vector_in_len_ch176_full_n = ap_const_logic_0)))) and (tmp_s_reg_131 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            vector_out_len_ch381_write <= ap_const_logic_1;
        else 
            vector_out_len_ch381_write <= ap_const_logic_0;
        end if; 
    end process;

    vector_out_length_fu_116_p1 <= vector_out_len_TDATA_int_regslice(12 - 1 downto 0);
end behav;
