// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RBM_sigmoid (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        systolic_out_dout,
        systolic_out_num_data_valid,
        systolic_out_fifo_cap,
        systolic_out_empty_n,
        systolic_out_read,
        stream_sigmoid_switch_TVALID,
        stream_vector_out_TREADY,
        stream_sigmoid_switch_TDATA,
        stream_sigmoid_switch_TREADY,
        stream_vector_out_TDATA,
        stream_vector_out_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter6_fsm_state7 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;
parameter    ap_ST_iter6_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [48:0] systolic_out_dout;
input  [7:0] systolic_out_num_data_valid;
input  [7:0] systolic_out_fifo_cap;
input   systolic_out_empty_n;
output   systolic_out_read;
input   stream_sigmoid_switch_TVALID;
input   stream_vector_out_TREADY;
input  [7:0] stream_sigmoid_switch_TDATA;
output   stream_sigmoid_switch_TREADY;
output  [127:0] stream_vector_out_TDATA;
output   stream_vector_out_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg systolic_out_read;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state0;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state0;
reg   [1:0] ap_CS_iter5_fsm;
wire    ap_CS_iter5_fsm_state0;
reg   [1:0] ap_CS_iter6_fsm;
wire    ap_CS_iter6_fsm_state0;
wire   [0:0] tmp_nbreadreq_fu_98_p3;
wire   [0:0] tmp_s_nbreadreq_fu_106_p3;
reg    ap_predicate_op16_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_CS_iter3_fsm_state4;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_CS_iter4_fsm_state5;
reg   [0:0] tmp_reg_404;
reg   [0:0] tmp_reg_404_pp0_iter4_reg;
reg   [0:0] tmp_s_reg_408;
reg   [0:0] tmp_s_reg_408_pp0_iter4_reg;
reg    ap_predicate_op66_write_state6;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
wire    ap_CS_iter5_fsm_state6;
reg   [0:0] tmp_reg_404_pp0_iter5_reg;
reg   [0:0] tmp_s_reg_408_pp0_iter5_reg;
reg    ap_predicate_op67_write_state7;
wire    regslice_both_stream_vector_out_U_apdone_blk;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state7_io;
wire    ap_CS_iter6_fsm_state7;
reg   [7:0] sigmoid_switch_V;
wire   [11:0] sigmoid_slope_V_address0;
reg    sigmoid_slope_V_ce0;
wire   [23:0] sigmoid_slope_V_q0;
wire   [11:0] sigmoid_bias_V_address0;
reg    sigmoid_bias_V_ce0;
wire   [25:0] sigmoid_bias_V_q0;
reg    stream_sigmoid_switch_TDATA_blk_n;
reg    systolic_out_blk_n;
reg    stream_vector_out_TDATA_blk_n;
wire   [0:0] tmp_reg_404_pp0_iter0_reg;
reg   [0:0] tmp_reg_404_pp0_iter1_reg;
reg   [0:0] tmp_reg_404_pp0_iter2_reg;
reg   [0:0] tmp_reg_404_pp0_iter3_reg;
wire   [0:0] tmp_s_reg_408_pp0_iter0_reg;
reg   [0:0] tmp_s_reg_408_pp0_iter1_reg;
reg   [0:0] tmp_s_reg_408_pp0_iter2_reg;
reg   [0:0] tmp_s_reg_408_pp0_iter3_reg;
wire   [47:0] systolic_out_data_V_1_fu_159_p1;
reg   [47:0] systolic_out_data_V_1_reg_412;
reg   [47:0] systolic_out_data_V_1_reg_412_pp0_iter1_reg;
reg   [47:0] systolic_out_data_V_1_reg_412_pp0_iter2_reg;
reg   [47:0] systolic_out_data_V_1_reg_412_pp0_iter3_reg;
reg   [47:0] systolic_out_data_V_1_reg_412_pp0_iter4_reg;
reg   [0:0] systolic_out_axis_last_1_reg_418;
reg   [0:0] systolic_out_axis_last_1_reg_418_pp0_iter1_reg;
reg   [0:0] systolic_out_axis_last_1_reg_418_pp0_iter2_reg;
reg   [0:0] systolic_out_axis_last_1_reg_418_pp0_iter3_reg;
reg   [0:0] systolic_out_axis_last_1_reg_418_pp0_iter4_reg;
reg   [0:0] tmp_198_reg_423;
reg   [0:0] tmp_198_reg_423_pp0_iter1_reg;
reg   [0:0] tmp_198_reg_423_pp0_iter2_reg;
reg   [0:0] tmp_198_reg_423_pp0_iter3_reg;
reg   [0:0] tmp_198_reg_423_pp0_iter4_reg;
wire   [47:0] sigmoid_temp_V_fu_179_p2;
reg   [47:0] sigmoid_temp_V_reg_429;
wire   [0:0] icmp_ln610_fu_270_p2;
reg   [0:0] icmp_ln610_reg_434;
reg   [0:0] icmp_ln610_reg_434_pp0_iter2_reg;
reg   [0:0] icmp_ln610_reg_434_pp0_iter3_reg;
reg   [0:0] icmp_ln610_reg_434_pp0_iter4_reg;
wire   [54:0] ret_V_132_fu_300_p2;
reg   [54:0] ret_V_132_reg_439;
reg  signed [54:0] ret_V_132_reg_439_pp0_iter2_reg;
wire   [0:0] icmp_ln1019_fu_316_p2;
reg   [0:0] icmp_ln1019_reg_454;
reg   [0:0] icmp_ln1019_reg_454_pp0_iter2_reg;
reg   [0:0] icmp_ln1019_reg_454_pp0_iter3_reg;
reg   [0:0] icmp_ln1019_reg_454_pp0_iter4_reg;
reg   [23:0] sigmoid_slope_V_load_reg_459;
reg   [25:0] rhs_67_reg_464;
reg   [25:0] rhs_67_reg_464_pp0_iter3_reg;
reg   [25:0] rhs_67_reg_464_pp0_iter4_reg;
wire   [78:0] grp_fu_328_p2;
reg   [78:0] r_V_192_reg_479;
wire   [63:0] zext_ln613_fu_306_p1;
wire   [47:0] sigmoid_temp_V_2_fu_191_p3;
wire   [73:0] t_fu_196_p3;
wire   [11:0] trunc_ln1003_fu_220_p1;
wire   [19:0] tmp_1_fu_224_p3;
wire   [31:0] trunc_ln_fu_204_p4;
wire   [0:0] icmp_ln1003_fu_232_p2;
wire   [31:0] ret_V_fu_238_p2;
wire   [0:0] p_Result_s_fu_214_p2;
wire   [31:0] select_ln1002_fu_244_p3;
wire   [31:0] ret_V_131_fu_252_p3;
wire   [19:0] tmp_199_fu_260_p4;
wire   [53:0] lhs_130_fu_284_p3;
wire   [49:0] r_V_193_fu_276_p3;
wire  signed [54:0] sext_ln1348_fu_292_p1;
wire  signed [54:0] sext_ln1348_1_fu_296_p1;
wire   [23:0] grp_fu_328_p1;
wire   [51:0] rhs_68_fu_334_p3;
wire   [78:0] zext_ln1347_fu_341_p1;
wire   [78:0] ret_V_130_fu_345_p2;
wire   [46:0] sigmoid_out_data_V_fu_350_p4;
wire   [46:0] sigmoid_out_data_V_1_fu_360_p3;
wire  signed [47:0] sext_ln596_fu_367_p1;
wire   [47:0] sigmoid_out_data_V_2_fu_371_p2;
wire   [47:0] sigmoid_out_data_V_3_fu_377_p3;
wire   [47:0] select_ln623_fu_384_p3;
wire   [64:0] tmp_2_fu_390_p4;
reg    grp_fu_328_ce;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg   [1:0] ap_NS_iter6_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_ST_iter2_fsm_state3_blk;
wire    ap_ST_iter3_fsm_state4_blk;
wire    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
reg    ap_ST_iter6_fsm_state7_blk;
wire    regslice_both_stream_sigmoid_switch_U_apdone_blk;
wire   [7:0] stream_sigmoid_switch_TDATA_int_regslice;
wire    stream_sigmoid_switch_TVALID_int_regslice;
reg    stream_sigmoid_switch_TREADY_int_regslice;
wire    regslice_both_stream_sigmoid_switch_U_ack_in;
wire   [127:0] stream_vector_out_TDATA_int_regslice;
reg    stream_vector_out_TVALID_int_regslice;
wire    stream_vector_out_TREADY_int_regslice;
wire    regslice_both_stream_vector_out_U_vld_out;
wire   [78:0] grp_fu_328_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
#0 ap_CS_iter6_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 sigmoid_switch_V = 8'd0;
end

RBM_sigmoid_sigmoid_slope_V_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sigmoid_slope_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_slope_V_address0),
    .ce0(sigmoid_slope_V_ce0),
    .q0(sigmoid_slope_V_q0)
);

RBM_sigmoid_sigmoid_bias_V_ROM_AUTO_1R #(
    .DataWidth( 26 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
sigmoid_bias_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_bias_V_address0),
    .ce0(sigmoid_bias_V_ce0),
    .q0(sigmoid_bias_V_q0)
);

RBM_mul_55s_24ns_79_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 55 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 79 ))
mul_55s_24ns_79_2_1_U117(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_132_reg_439_pp0_iter2_reg),
    .din1(grp_fu_328_p1),
    .ce(grp_fu_328_ce),
    .dout(grp_fu_328_p2)
);

RBM_regslice_both #(
    .DataWidth( 8 ))
regslice_both_stream_sigmoid_switch_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(stream_sigmoid_switch_TDATA),
    .vld_in(stream_sigmoid_switch_TVALID),
    .ack_in(regslice_both_stream_sigmoid_switch_U_ack_in),
    .data_out(stream_sigmoid_switch_TDATA_int_regslice),
    .vld_out(stream_sigmoid_switch_TVALID_int_regslice),
    .ack_out(stream_sigmoid_switch_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_sigmoid_switch_U_apdone_blk)
);

RBM_regslice_both #(
    .DataWidth( 128 ))
regslice_both_stream_vector_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(stream_vector_out_TDATA_int_regslice),
    .vld_in(stream_vector_out_TVALID_int_regslice),
    .ack_in(stream_vector_out_TREADY_int_regslice),
    .data_out(stream_vector_out_TDATA),
    .vld_out(regslice_both_stream_vector_out_U_vld_out),
    .ack_out(stream_vector_out_TREADY),
    .apdone_blk(regslice_both_stream_vector_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
    end else begin
        ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2) & (tmp_s_reg_408_pp0_iter0_reg == 1'd1) & (tmp_reg_404_pp0_iter0_reg == 1'd0))) begin
        icmp_ln1019_reg_454 <= icmp_ln1019_fu_316_p2;
        icmp_ln610_reg_434 <= icmp_ln610_fu_270_p2;
        ret_V_132_reg_439[54 : 6] <= ret_V_132_fu_300_p2[54 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln1019_reg_454_pp0_iter2_reg <= icmp_ln1019_reg_454;
        icmp_ln610_reg_434_pp0_iter2_reg <= icmp_ln610_reg_434;
        ret_V_132_reg_439_pp0_iter2_reg[54 : 6] <= ret_V_132_reg_439[54 : 6];
        systolic_out_axis_last_1_reg_418_pp0_iter2_reg <= systolic_out_axis_last_1_reg_418_pp0_iter1_reg;
        systolic_out_data_V_1_reg_412_pp0_iter2_reg <= systolic_out_data_V_1_reg_412_pp0_iter1_reg;
        tmp_198_reg_423_pp0_iter2_reg <= tmp_198_reg_423_pp0_iter1_reg;
        tmp_reg_404_pp0_iter2_reg <= tmp_reg_404_pp0_iter1_reg;
        tmp_s_reg_408_pp0_iter2_reg <= tmp_s_reg_408_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln1019_reg_454_pp0_iter3_reg <= icmp_ln1019_reg_454_pp0_iter2_reg;
        icmp_ln610_reg_434_pp0_iter3_reg <= icmp_ln610_reg_434_pp0_iter2_reg;
        rhs_67_reg_464_pp0_iter3_reg <= rhs_67_reg_464;
        systolic_out_axis_last_1_reg_418_pp0_iter3_reg <= systolic_out_axis_last_1_reg_418_pp0_iter2_reg;
        systolic_out_data_V_1_reg_412_pp0_iter3_reg <= systolic_out_data_V_1_reg_412_pp0_iter2_reg;
        tmp_198_reg_423_pp0_iter3_reg <= tmp_198_reg_423_pp0_iter2_reg;
        tmp_reg_404_pp0_iter3_reg <= tmp_reg_404_pp0_iter2_reg;
        tmp_s_reg_408_pp0_iter3_reg <= tmp_s_reg_408_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        icmp_ln1019_reg_454_pp0_iter4_reg <= icmp_ln1019_reg_454_pp0_iter3_reg;
        icmp_ln610_reg_434_pp0_iter4_reg <= icmp_ln610_reg_434_pp0_iter3_reg;
        rhs_67_reg_464_pp0_iter4_reg <= rhs_67_reg_464_pp0_iter3_reg;
        systolic_out_axis_last_1_reg_418_pp0_iter4_reg <= systolic_out_axis_last_1_reg_418_pp0_iter3_reg;
        systolic_out_data_V_1_reg_412_pp0_iter4_reg <= systolic_out_data_V_1_reg_412_pp0_iter3_reg;
        tmp_198_reg_423_pp0_iter4_reg <= tmp_198_reg_423_pp0_iter3_reg;
        tmp_reg_404_pp0_iter4_reg <= tmp_reg_404_pp0_iter3_reg;
        tmp_s_reg_408_pp0_iter4_reg <= tmp_s_reg_408_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5) & (icmp_ln1019_reg_454_pp0_iter3_reg == 1'd0) & (icmp_ln610_reg_434_pp0_iter3_reg == 1'd0) & (tmp_s_reg_408_pp0_iter3_reg == 1'd1) & (tmp_reg_404_pp0_iter3_reg == 1'd0))) begin
        r_V_192_reg_479 <= grp_fu_328_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3) & (tmp_s_reg_408_pp0_iter1_reg == 1'd1) & (tmp_reg_404_pp0_iter1_reg == 1'd0))) begin
        rhs_67_reg_464 <= sigmoid_bias_V_q0;
        sigmoid_slope_V_load_reg_459 <= sigmoid_slope_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sigmoid_switch_V <= stream_sigmoid_switch_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (tmp_s_nbreadreq_fu_106_p3 == 1'd1) & (tmp_nbreadreq_fu_98_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        sigmoid_temp_V_reg_429 <= sigmoid_temp_V_fu_179_p2;
        systolic_out_axis_last_1_reg_418 <= systolic_out_dout[32'd48];
        systolic_out_data_V_1_reg_412 <= systolic_out_data_V_1_fu_159_p1;
        tmp_198_reg_423 <= systolic_out_dout[32'd47];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        systolic_out_axis_last_1_reg_418_pp0_iter1_reg <= systolic_out_axis_last_1_reg_418;
        systolic_out_data_V_1_reg_412_pp0_iter1_reg <= systolic_out_data_V_1_reg_412;
        tmp_198_reg_423_pp0_iter1_reg <= tmp_198_reg_423;
        tmp_reg_404_pp0_iter1_reg <= tmp_reg_404;
        tmp_s_reg_408_pp0_iter1_reg <= tmp_s_reg_408;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_reg_404 <= tmp_nbreadreq_fu_98_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
        tmp_reg_404_pp0_iter5_reg <= tmp_reg_404_pp0_iter4_reg;
        tmp_s_reg_408_pp0_iter5_reg <= tmp_s_reg_408_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (tmp_nbreadreq_fu_98_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_s_reg_408 <= tmp_s_nbreadreq_fu_106_p3;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

assign ap_ST_iter2_fsm_state3_blk = 1'b0;

assign ap_ST_iter3_fsm_state4_blk = 1'b0;

assign ap_ST_iter4_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)))) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) begin
        ap_ST_iter6_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_iter6_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))) & (1'b1 == ap_CS_iter6_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter6_fsm_state0) & (1'b1 == ap_CS_iter5_fsm_state0) & (1'b1 == ap_CS_iter4_fsm_state0) & (1'b1 == ap_CS_iter3_fsm_state0) & (1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4)))) begin
        grp_fu_328_ce = 1'b1;
    end else begin
        grp_fu_328_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sigmoid_bias_V_ce0 = 1'b1;
    end else begin
        sigmoid_bias_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        sigmoid_slope_V_ce0 = 1'b1;
    end else begin
        sigmoid_slope_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        stream_sigmoid_switch_TDATA_blk_n = stream_sigmoid_switch_TVALID_int_regslice;
    end else begin
        stream_sigmoid_switch_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (tmp_nbreadreq_fu_98_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        stream_sigmoid_switch_TREADY_int_regslice = 1'b1;
    end else begin
        stream_sigmoid_switch_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter6_fsm_state7) & (ap_predicate_op67_write_state7 == 1'b1)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_predicate_op66_write_state6 == 1'b1)))) begin
        stream_vector_out_TDATA_blk_n = stream_vector_out_TREADY_int_regslice;
    end else begin
        stream_vector_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))))) & (1'b1 == ap_CS_iter5_fsm_state6) & (ap_predicate_op66_write_state6 == 1'b1))) begin
        stream_vector_out_TVALID_int_regslice = 1'b1;
    end else begin
        stream_vector_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op16_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        systolic_out_blk_n = systolic_out_empty_n;
    end else begin
        systolic_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (ap_predicate_op16_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        systolic_out_read = 1'b1;
    end else begin
        systolic_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & ~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b0 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b0 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))))) & (1'b0 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter6_fsm)
        ap_ST_iter6_fsm_state7 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))) & ~((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))) & ((1'b0 == ap_CS_iter5_fsm_state6) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1))))))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end
        end
        ap_ST_iter6_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (1'b1 == ap_block_state6_io) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1)) | ((1'b1 == ap_CS_iter6_fsm_state7) & ((1'b1 == ap_block_state7_io) | (regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1))))) & (1'b1 == ap_CS_iter5_fsm_state6))) begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state7;
            end else begin
                ap_NS_iter6_fsm = ap_ST_iter6_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter6_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state0 = ap_CS_iter3_fsm[32'd0];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state0 = ap_CS_iter4_fsm[32'd0];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state0 = ap_CS_iter5_fsm[32'd0];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

assign ap_CS_iter6_fsm_state0 = ap_CS_iter6_fsm[32'd0];

assign ap_CS_iter6_fsm_state7 = ap_CS_iter6_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((tmp_nbreadreq_fu_98_p3 == 1'd1) & (stream_sigmoid_switch_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op16_read_state1 == 1'b1) & (systolic_out_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op66_write_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state7_io = ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = ((regslice_both_stream_vector_out_U_apdone_blk == 1'b1) | ((stream_vector_out_TREADY_int_regslice == 1'b0) & (ap_predicate_op67_write_state7 == 1'b1)));
end

always @ (*) begin
    ap_predicate_op16_read_state1 = ((tmp_s_nbreadreq_fu_106_p3 == 1'd1) & (tmp_nbreadreq_fu_98_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_write_state6 = ((tmp_s_reg_408_pp0_iter4_reg == 1'd1) & (tmp_reg_404_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op67_write_state7 = ((tmp_s_reg_408_pp0_iter5_reg == 1'd1) & (tmp_reg_404_pp0_iter5_reg == 1'd0));
end

assign grp_fu_328_p1 = grp_fu_328_p10;

assign grp_fu_328_p10 = sigmoid_slope_V_load_reg_459;

assign icmp_ln1003_fu_232_p2 = ((tmp_1_fu_224_p3 == 20'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_316_p2 = ((sigmoid_switch_V == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln610_fu_270_p2 = (($signed(tmp_199_fu_260_p4) > $signed(20'd0)) ? 1'b1 : 1'b0);

assign lhs_130_fu_284_p3 = {{sigmoid_temp_V_2_fu_191_p3}, {6'd0}};

assign p_Result_s_fu_214_p2 = (($signed(t_fu_196_p3) < $signed(74'd18889465931478580592641)) ? 1'b1 : 1'b0);

assign r_V_193_fu_276_p3 = {{ret_V_131_fu_252_p3}, {18'd0}};

assign ret_V_130_fu_345_p2 = (r_V_192_reg_479 + zext_ln1347_fu_341_p1);

assign ret_V_131_fu_252_p3 = ((p_Result_s_fu_214_p2[0:0] == 1'b1) ? select_ln1002_fu_244_p3 : trunc_ln_fu_204_p4);

assign ret_V_132_fu_300_p2 = ($signed(sext_ln1348_fu_292_p1) - $signed(sext_ln1348_1_fu_296_p1));

assign ret_V_fu_238_p2 = (trunc_ln_fu_204_p4 + 32'd1);

assign rhs_68_fu_334_p3 = {{rhs_67_reg_464_pp0_iter4_reg}, {26'd0}};

assign select_ln1002_fu_244_p3 = ((icmp_ln1003_fu_232_p2[0:0] == 1'b1) ? trunc_ln_fu_204_p4 : ret_V_fu_238_p2);

assign select_ln623_fu_384_p3 = ((icmp_ln1019_reg_454_pp0_iter4_reg[0:0] == 1'b1) ? systolic_out_data_V_1_reg_412_pp0_iter4_reg : sigmoid_out_data_V_3_fu_377_p3);

assign sext_ln1348_1_fu_296_p1 = $signed(r_V_193_fu_276_p3);

assign sext_ln1348_fu_292_p1 = $signed(lhs_130_fu_284_p3);

assign sext_ln596_fu_367_p1 = $signed(sigmoid_out_data_V_1_fu_360_p3);

assign sigmoid_bias_V_address0 = zext_ln613_fu_306_p1;

assign sigmoid_out_data_V_1_fu_360_p3 = ((icmp_ln610_reg_434_pp0_iter4_reg[0:0] == 1'b1) ? 47'd1048576 : sigmoid_out_data_V_fu_350_p4);

assign sigmoid_out_data_V_2_fu_371_p2 = ($signed(48'd1048576) - $signed(sext_ln596_fu_367_p1));

assign sigmoid_out_data_V_3_fu_377_p3 = ((tmp_198_reg_423_pp0_iter4_reg[0:0] == 1'b1) ? sigmoid_out_data_V_2_fu_371_p2 : sext_ln596_fu_367_p1);

assign sigmoid_out_data_V_fu_350_p4 = {{ret_V_130_fu_345_p2[78:32]}};

assign sigmoid_slope_V_address0 = zext_ln613_fu_306_p1;

assign sigmoid_temp_V_2_fu_191_p3 = ((tmp_198_reg_423[0:0] == 1'b1) ? sigmoid_temp_V_reg_429 : systolic_out_data_V_1_reg_412);

assign sigmoid_temp_V_fu_179_p2 = (48'd0 - systolic_out_data_V_1_fu_159_p1);

assign stream_sigmoid_switch_TREADY = regslice_both_stream_sigmoid_switch_U_ack_in;

assign stream_vector_out_TDATA_int_regslice = tmp_2_fu_390_p4;

assign stream_vector_out_TVALID = regslice_both_stream_vector_out_U_vld_out;

assign systolic_out_data_V_1_fu_159_p1 = systolic_out_dout[47:0];

assign t_fu_196_p3 = {{sigmoid_temp_V_2_fu_191_p3}, {26'd0}};

assign tmp_199_fu_260_p4 = {{ret_V_131_fu_252_p3[31:12]}};

assign tmp_1_fu_224_p3 = {{trunc_ln1003_fu_220_p1}, {8'd0}};

assign tmp_2_fu_390_p4 = {{{systolic_out_axis_last_1_reg_418_pp0_iter4_reg}, {16'd0}}, {select_ln623_fu_384_p3}};

assign tmp_nbreadreq_fu_98_p3 = stream_sigmoid_switch_TVALID_int_regslice;

assign tmp_reg_404_pp0_iter0_reg = tmp_reg_404;

assign tmp_s_nbreadreq_fu_106_p3 = systolic_out_empty_n;

assign tmp_s_reg_408_pp0_iter0_reg = tmp_s_reg_408;

assign trunc_ln1003_fu_220_p1 = sigmoid_temp_V_2_fu_191_p3[11:0];

assign trunc_ln_fu_204_p4 = {{sigmoid_temp_V_2_fu_191_p3[43:12]}};

assign zext_ln1347_fu_341_p1 = rhs_68_fu_334_p3;

assign zext_ln613_fu_306_p1 = ret_V_131_fu_252_p3;

always @ (posedge ap_clk) begin
    ret_V_132_reg_439[5:0] <= 6'b000000;
    ret_V_132_reg_439_pp0_iter2_reg[5:0] <= 6'b000000;
end

endmodule //RBM_sigmoid
