// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module RBM_double_buffer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_vector_in_TVALID,
        vector_in_len_ch176_dout,
        vector_in_len_ch176_num_data_valid,
        vector_in_len_ch176_fifo_cap,
        vector_in_len_ch176_empty_n,
        vector_in_len_ch176_read,
        control_ch173_dout,
        control_ch173_num_data_valid,
        control_ch173_fifo_cap,
        control_ch173_empty_n,
        control_ch173_read,
        buffer_out_din,
        buffer_out_num_data_valid,
        buffer_out_fifo_cap,
        buffer_out_full_n,
        buffer_out_write,
        stream_vector_in_TDATA,
        stream_vector_in_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   stream_vector_in_TVALID;
input  [11:0] vector_in_len_ch176_dout;
input  [7:0] vector_in_len_ch176_num_data_valid;
input  [7:0] vector_in_len_ch176_fifo_cap;
input   vector_in_len_ch176_empty_n;
output   vector_in_len_ch176_read;
input  [7:0] control_ch173_dout;
input  [7:0] control_ch173_num_data_valid;
input  [7:0] control_ch173_fifo_cap;
input   control_ch173_empty_n;
output   control_ch173_read;
output  [20:0] buffer_out_din;
input  [10:0] buffer_out_num_data_valid;
input  [10:0] buffer_out_fifo_cap;
input   buffer_out_full_n;
output   buffer_out_write;
input  [31:0] stream_vector_in_TDATA;
output   stream_vector_in_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg vector_in_len_ch176_read;
reg control_ch173_read;
reg buffer_out_write;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state0;
wire   [0:0] tmp_nbreadreq_fu_174_p3;
wire   [0:0] and_ln143_fu_365_p2;
reg    ap_predicate_op29_read_state1;
wire   [0:0] tmp_s_nbreadreq_fu_196_p3;
reg    ap_predicate_op116_read_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    buffer_0_full_n;
reg    buffer_0_write;
reg   [0:0] tmp_reg_960;
reg   [7:0] control_V_1_load_reg_964;
reg   [0:0] and_ln143_reg_968;
reg   [0:0] buffer_write_select_load_reg_991;
reg    ap_predicate_op128_write_state2;
wire    buffer_1_full_n;
reg    buffer_1_write;
reg    ap_predicate_op129_write_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [0:0] tmp_reg_960_pp0_iter1_reg;
reg   [7:0] control_V_1_load_reg_964_pp0_iter1_reg;
reg   [0:0] buffer_data_read_valid_load_reg_972;
reg   [0:0] buffer_data_read_valid_load_reg_972_pp0_iter1_reg;
reg    ap_predicate_op142_write_state3;
wire   [20:0] buffer_1_dout;
wire    buffer_1_empty_n;
reg    buffer_1_read;
reg   [0:0] buffer0_read_en_load_reg_1000;
reg   [0:0] buffer0_read_en_load_reg_1000_pp0_iter1_reg;
reg   [0:0] buffer1_read_en_load_reg_1004;
reg   [0:0] buffer1_read_en_load_reg_1004_pp0_iter1_reg;
reg    ap_predicate_op144_read_state3;
wire   [20:0] buffer_0_dout;
wire    buffer_0_empty_n;
reg    buffer_0_read;
reg    ap_predicate_op151_read_state3;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [7:0] control_V_1;
reg   [11:0] vector_in_length_V_1;
reg   [11:0] vector_in_length_minus_1_V;
reg   [0:0] buffer_write_en;
reg   [0:0] buffer_data_read_valid;
reg   [0:0] buffer_data_read_first_data;
reg   [0:0] buffer_data_read_last_data;
reg   [0:0] buffer_data_read_axis_last;
reg   [0:0] buffer_data_read_pad_zero;
reg   [15:0] buffer_data_read_data_V;
reg   [0:0] buffer_write_select;
reg   [0:0] buffer0_read_en;
reg   [15:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4;
reg   [15:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5;
reg   [0:0] buffer1_read_en;
reg   [0:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_2;
reg   [0:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status;
reg   [0:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_3;
reg   [0:0] double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_1;
reg    control_ch173_blk_n;
reg    vector_in_len_ch176_blk_n;
reg    stream_vector_in_TDATA_blk_n;
reg    buffer_out_blk_n;
wire   [0:0] buffer_data_read_valid_load_load_fu_371_p1;
reg   [0:0] buffer_data_read_first_data_load_reg_976;
reg   [0:0] buffer_data_read_first_data_load_reg_976_pp0_iter1_reg;
reg   [0:0] buffer_data_read_last_data_load_reg_981;
reg   [0:0] buffer_data_read_last_data_load_reg_981_pp0_iter1_reg;
wire   [15:0] stream_data_v_data_V_fu_383_p1;
reg   [15:0] stream_data_v_data_V_reg_986;
wire   [0:0] buffer_write_select_load_load_fu_387_p1;
reg   [0:0] tmp_204_reg_995;
wire   [0:0] buffer0_read_en_load_load_fu_399_p1;
wire   [0:0] buffer1_read_en_load_load_fu_411_p1;
reg   [0:0] ap_phi_mux_i_op_assign_2_phi_fu_248_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_i_op_assign_2_reg_245;
reg   [0:0] ap_phi_mux_i_op_assign_phi_fu_262_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_i_op_assign_reg_259;
reg   [0:0] ap_phi_mux_i_op_assign_3_phi_fu_276_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_i_op_assign_3_reg_273;
reg   [0:0] ap_phi_mux_i_op_assign_1_phi_fu_290_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_i_op_assign_1_reg_287;
reg   [0:0] ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_reg_301;
wire   [0:0] icmp_ln1031_fu_497_p2;
wire   [0:0] icmp_ln1039_fu_535_p2;
reg   [0:0] ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_reg_314;
reg   [0:0] ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_reg_327;
wire   [0:0] icmp_ln1031_1_fu_553_p2;
wire   [0:0] icmp_ln1039_1_fu_591_p2;
reg   [0:0] ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_reg_340;
wire   [11:0] add_ln186_fu_725_p2;
wire   [0:0] or_ln214_fu_609_p2;
wire   [0:0] icmp_ln1019_2_fu_431_p2;
wire   [0:0] icmp_ln1019_fu_465_p2;
wire   [0:0] icmp_ln1019_3_fu_443_p2;
wire   [0:0] icmp_ln1019_1_fu_477_p2;
wire   [0:0] and_ln215_fu_627_p2;
wire   [15:0] add_ln223_fu_673_p2;
wire   [15:0] add_ln225_fu_707_p2;
wire   [0:0] tmp_3_nbreadreq_fu_182_p3;
wire   [20:0] p_s_fu_743_p5;
wire   [15:0] zext_ln1019_1_fu_427_p1;
wire   [15:0] zext_ln1019_fu_461_p1;
wire   [15:0] zext_ln1031_fu_493_p1;
wire   [14:0] tmp_209_fu_525_p4;
wire   [14:0] tmp_210_fu_581_p4;
wire   [0:0] xor_ln215_fu_621_p2;
wire   [1:0] select_ln1496_fu_655_p3;
wire   [1:0] zext_ln1627_fu_651_p1;
wire   [1:0] add_ln1496_fu_663_p2;
wire  signed [15:0] sext_ln223_fu_669_p1;
wire   [1:0] select_ln1496_1_fu_689_p3;
wire   [1:0] zext_ln1627_1_fu_685_p1;
wire   [1:0] add_ln1496_1_fu_697_p2;
wire  signed [15:0] sext_ln225_fu_703_p1;
wire   [63:0] or_ln147_3_fu_767_p11;
wire   [63:0] or_ln147_fu_789_p2;
wire   [15:0] tmp_4_fu_827_p4;
wire   [0:0] tmp_203_fu_819_p3;
wire   [0:0] tmp_202_fu_811_p3;
wire   [0:0] tmp_201_fu_803_p3;
wire   [0:0] tmp_200_fu_795_p3;
wire   [20:0] or_ln147_8_fu_837_p7;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_stream_vector_in_U_apdone_blk;
wire   [31:0] stream_vector_in_TDATA_int_regslice;
wire    stream_vector_in_TVALID_int_regslice;
reg    stream_vector_in_TREADY_int_regslice;
wire    regslice_both_stream_vector_in_U_ack_in;
reg    ap_condition_744;
reg    ap_condition_697;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 control_V_1 = 8'd0;
#0 vector_in_length_V_1 = 12'd0;
#0 vector_in_length_minus_1_V = 12'd0;
#0 buffer_write_en = 1'd0;
#0 buffer_data_read_valid = 1'd0;
#0 buffer_data_read_first_data = 1'd0;
#0 buffer_data_read_last_data = 1'd0;
#0 buffer_data_read_axis_last = 1'd0;
#0 buffer_data_read_pad_zero = 1'd0;
#0 buffer_data_read_data_V = 16'd0;
#0 buffer_write_select = 1'd0;
#0 buffer0_read_en = 1'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4 = 16'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5 = 16'd0;
#0 buffer1_read_en = 1'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_2 = 1'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status = 1'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_3 = 1'd0;
#0 double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_1 = 1'd0;
end

RBM_fifo_w21_d1024_A buffer_0_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_s_fu_743_p5),
    .if_full_n(buffer_0_full_n),
    .if_write(buffer_0_write),
    .if_dout(buffer_0_dout),
    .if_empty_n(buffer_0_empty_n),
    .if_read(buffer_0_read)
);

RBM_fifo_w21_d1024_A buffer_1_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_s_fu_743_p5),
    .if_full_n(buffer_1_full_n),
    .if_write(buffer_1_write),
    .if_dout(buffer_1_dout),
    .if_empty_n(buffer_1_empty_n),
    .if_read(buffer_1_read)
);

RBM_regslice_both #(
    .DataWidth( 32 ))
regslice_both_stream_vector_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(stream_vector_in_TDATA),
    .vld_in(stream_vector_in_TVALID),
    .ack_in(regslice_both_stream_vector_in_U_ack_in),
    .data_out(stream_vector_in_TDATA_int_regslice),
    .vld_out(stream_vector_in_TVALID_int_regslice),
    .ack_out(stream_vector_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_vector_in_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_744)) begin
        if ((buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd1)) begin
            buffer_data_read_axis_last <= buffer_0_dout[32'd3];
        end else if (((buffer1_read_en_load_reg_1004_pp0_iter1_reg == 1'd1) & (buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd0))) begin
            buffer_data_read_axis_last <= buffer_1_dout[32'd3];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_744)) begin
        if ((buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd1)) begin
            buffer_data_read_data_V <= {{buffer_0_dout[20:5]}};
        end else if (((buffer1_read_en_load_reg_1004_pp0_iter1_reg == 1'd1) & (buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd0))) begin
            buffer_data_read_data_V <= {{buffer_1_dout[20:5]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if ((buffer0_read_en_load_load_fu_399_p1 == 1'd1)) begin
            buffer_data_read_first_data <= icmp_ln1019_fu_465_p2;
        end else if (((buffer1_read_en_load_load_fu_411_p1 == 1'd1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0))) begin
            buffer_data_read_first_data <= icmp_ln1019_2_fu_431_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if ((buffer0_read_en_load_load_fu_399_p1 == 1'd1)) begin
            buffer_data_read_last_data <= icmp_ln1019_1_fu_477_p2;
        end else if (((buffer1_read_en_load_load_fu_411_p1 == 1'd1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0))) begin
            buffer_data_read_last_data <= icmp_ln1019_3_fu_443_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_744)) begin
        if ((buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd1)) begin
            buffer_data_read_pad_zero <= buffer_0_dout[32'd4];
        end else if (((buffer1_read_en_load_reg_1004_pp0_iter1_reg == 1'd1) & (buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd0))) begin
            buffer_data_read_pad_zero <= buffer_1_dout[32'd4];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (buffer1_read_en_load_load_fu_411_p1 == 1'd1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0)) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd1)))) begin
        buffer_data_read_valid <= 1'd1;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (buffer1_read_en_load_load_fu_411_p1 == 1'd0) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0))) begin
        buffer_data_read_valid <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if (((icmp_ln1039_fu_535_p2 == 1'd1) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status <= 1'd0;
        end else if ((icmp_ln1031_fu_497_p2 == 1'd0)) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if (((icmp_ln1039_1_fu_591_p2 == 1'd1) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_1 <= 1'd0;
        end else if ((icmp_ln1031_1_fu_553_p2 == 1'd0)) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_1 <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if (((icmp_ln1039_fu_535_p2 == 1'd1) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_2 <= 1'd1;
        end else if ((icmp_ln1031_fu_497_p2 == 1'd0)) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_2 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_697)) begin
        if (((icmp_ln1039_1_fu_591_p2 == 1'd1) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_3 <= 1'd1;
        end else if ((icmp_ln1031_1_fu_553_p2 == 1'd0)) begin
            double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_3 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        and_ln143_reg_968 <= and_ln143_fu_365_p2;
        buffer0_read_en <= ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6;
        buffer0_read_en_load_reg_1000 <= buffer0_read_en;
        buffer1_read_en <= ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6;
        buffer_data_read_valid_load_reg_972 <= buffer_data_read_valid;
        buffer_write_en <= or_ln214_fu_609_p2;
        buffer_write_select <= and_ln215_fu_627_p2;
        double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4 <= add_ln223_fu_673_p2;
        double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5 <= add_ln225_fu_707_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        buffer0_read_en_load_reg_1000_pp0_iter1_reg <= buffer0_read_en_load_reg_1000;
        buffer1_read_en_load_reg_1004_pp0_iter1_reg <= buffer1_read_en_load_reg_1004;
        buffer_data_read_first_data_load_reg_976_pp0_iter1_reg <= buffer_data_read_first_data_load_reg_976;
        buffer_data_read_last_data_load_reg_981_pp0_iter1_reg <= buffer_data_read_last_data_load_reg_981;
        buffer_data_read_valid_load_reg_972_pp0_iter1_reg <= buffer_data_read_valid_load_reg_972;
        control_V_1_load_reg_964_pp0_iter1_reg <= control_V_1_load_reg_964;
        tmp_reg_960_pp0_iter1_reg <= tmp_reg_960;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0))) begin
        buffer1_read_en_load_reg_1004 <= buffer1_read_en;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (buffer_data_read_valid_load_load_fu_371_p1 == 1'd1))) begin
        buffer_data_read_first_data_load_reg_976 <= buffer_data_read_first_data;
        buffer_data_read_last_data_load_reg_981 <= buffer_data_read_last_data;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        buffer_write_select_load_reg_991 <= buffer_write_select;
        stream_data_v_data_V_reg_986 <= stream_data_v_data_V_fu_383_p1;
        tmp_204_reg_995 <= stream_vector_in_TDATA_int_regslice[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (tmp_nbreadreq_fu_174_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        control_V_1 <= control_ch173_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        control_V_1_load_reg_964 <= control_V_1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        tmp_reg_960 <= tmp_nbreadreq_fu_174_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (tmp_s_nbreadreq_fu_196_p3 == 1'd1) & (control_V_1 == 8'd1) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        vector_in_length_V_1 <= vector_in_len_ch176_dout;
        vector_in_length_minus_1_V <= add_ln186_fu_725_p2;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state0) & (1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0))) begin
        if (((icmp_ln1039_1_fu_591_p2 == 1'd0) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6 = double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_3;
        end else if (((icmp_ln1039_1_fu_591_p2 == 1'd1) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6 = 1'd1;
        end else if ((icmp_ln1031_1_fu_553_p2 == 1'd0)) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6 = 1'd0;
        end else begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_reg_327;
        end
    end else begin
        ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_reg_327;
    end
end

always @ (*) begin
    if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0))) begin
        if (((icmp_ln1039_fu_535_p2 == 1'd0) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 = double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_2;
        end else if (((icmp_ln1039_fu_535_p2 == 1'd1) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 = 1'd1;
        end else if ((icmp_ln1031_fu_497_p2 == 1'd0)) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 = 1'd0;
        end else begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_reg_301;
        end
    end else begin
        ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_reg_301;
    end
end

always @ (*) begin
    if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0))) begin
        if (((icmp_ln1039_1_fu_591_p2 == 1'd0) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6 = double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_1;
        end else if (((icmp_ln1039_1_fu_591_p2 == 1'd1) & (icmp_ln1031_1_fu_553_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6 = 1'd0;
        end else if ((icmp_ln1031_1_fu_553_p2 == 1'd0)) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6 = 1'd1;
        end else begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_reg_340;
        end
    end else begin
        ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_phi_fu_343_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_reg_340;
    end
end

always @ (*) begin
    if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0))) begin
        if (((icmp_ln1039_fu_535_p2 == 1'd0) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6 = double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status;
        end else if (((icmp_ln1039_fu_535_p2 == 1'd1) & (icmp_ln1031_fu_497_p2 == 1'd1))) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6 = 1'd0;
        end else if ((icmp_ln1031_fu_497_p2 == 1'd0)) begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6 = 1'd1;
        end else begin
            ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_reg_314;
        end
    end else begin
        ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_phi_fu_317_p6 = ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_reg_314;
    end
end

always @ (*) begin
    if ((((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer1_read_en_load_load_fu_411_p1 == 1'd1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0)) | ((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer1_read_en_load_load_fu_411_p1 == 1'd0) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0)))) begin
        ap_phi_mux_i_op_assign_1_phi_fu_290_p6 = 1'd0;
    end else if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer0_read_en_load_load_fu_399_p1 == 1'd1))) begin
        ap_phi_mux_i_op_assign_1_phi_fu_290_p6 = 1'd1;
    end else begin
        ap_phi_mux_i_op_assign_1_phi_fu_290_p6 = ap_phi_reg_pp0_iter0_i_op_assign_1_reg_287;
    end
end

always @ (*) begin
    if ((((1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer_write_select_load_load_fu_387_p1 == 1'd0)) | ((control_V_1 == 8'd4) & (1'd0 == and_ln143_fu_365_p2) & (tmp_nbreadreq_fu_174_p3 == 1'd0)))) begin
        ap_phi_mux_i_op_assign_2_phi_fu_248_p6 = 1'd0;
    end else if (((1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer_write_select_load_load_fu_387_p1 == 1'd1))) begin
        ap_phi_mux_i_op_assign_2_phi_fu_248_p6 = 1'd1;
    end else begin
        ap_phi_mux_i_op_assign_2_phi_fu_248_p6 = ap_phi_reg_pp0_iter0_i_op_assign_2_reg_245;
    end
end

always @ (*) begin
    if (((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer1_read_en_load_load_fu_411_p1 == 1'd1) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0))) begin
        ap_phi_mux_i_op_assign_3_phi_fu_276_p6 = 1'd1;
    end else if ((((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer1_read_en_load_load_fu_411_p1 == 1'd0) & (buffer0_read_en_load_load_fu_399_p1 == 1'd0)) | ((control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer0_read_en_load_load_fu_399_p1 == 1'd1)))) begin
        ap_phi_mux_i_op_assign_3_phi_fu_276_p6 = 1'd0;
    end else begin
        ap_phi_mux_i_op_assign_3_phi_fu_276_p6 = ap_phi_reg_pp0_iter0_i_op_assign_3_reg_273;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer_write_select_load_load_fu_387_p1 == 1'd0))) begin
        ap_phi_mux_i_op_assign_phi_fu_262_p6 = 1'd1;
    end else if ((((1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (buffer_write_select_load_load_fu_387_p1 == 1'd1)) | ((control_V_1 == 8'd4) & (1'd0 == and_ln143_fu_365_p2) & (tmp_nbreadreq_fu_174_p3 == 1'd0)))) begin
        ap_phi_mux_i_op_assign_phi_fu_262_p6 = 1'd0;
    end else begin
        ap_phi_mux_i_op_assign_phi_fu_262_p6 = ap_phi_reg_pp0_iter0_i_op_assign_reg_259;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op151_read_state3 == 1'b1))) begin
        buffer_0_read = 1'b1;
    end else begin
        buffer_0_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op128_write_state2 == 1'b1))) begin
        buffer_0_write = 1'b1;
    end else begin
        buffer_0_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op144_read_state3 == 1'b1))) begin
        buffer_1_read = 1'b1;
    end else begin
        buffer_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2) & (ap_predicate_op129_write_state2 == 1'b1))) begin
        buffer_1_write = 1'b1;
    end else begin
        buffer_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op142_write_state3 == 1'b1))) begin
        buffer_out_blk_n = buffer_out_full_n;
    end else begin
        buffer_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (ap_predicate_op142_write_state3 == 1'b1))) begin
        buffer_out_write = 1'b1;
    end else begin
        buffer_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (tmp_nbreadreq_fu_174_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        control_ch173_blk_n = control_ch173_empty_n;
    end else begin
        control_ch173_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (tmp_nbreadreq_fu_174_p3 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        control_ch173_read = 1'b1;
    end else begin
        control_ch173_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        stream_vector_in_TDATA_blk_n = stream_vector_in_TVALID_int_regslice;
    end else begin
        stream_vector_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (ap_predicate_op29_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        stream_vector_in_TREADY_int_regslice = 1'b1;
    end else begin
        stream_vector_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (ap_predicate_op116_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b1))) begin
        vector_in_len_ch176_blk_n = vector_in_len_ch176_empty_n;
    end else begin
        vector_in_len_ch176_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (ap_predicate_op116_read_state1 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        vector_in_len_ch176_read = 1'b1;
    end else begin
        vector_in_len_ch176_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1))) & ~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & ~(((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((ap_done_reg == 1'b1) | ((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln1496_1_fu_697_p2 = (select_ln1496_1_fu_689_p3 + zext_ln1627_1_fu_685_p1);

assign add_ln1496_fu_663_p2 = (select_ln1496_fu_655_p3 + zext_ln1627_fu_651_p1);

assign add_ln186_fu_725_p2 = ($signed(vector_in_len_ch176_dout) + $signed(12'd4095));

assign add_ln223_fu_673_p2 = ($signed(double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4) + $signed(sext_ln223_fu_669_p1));

assign add_ln225_fu_707_p2 = ($signed(double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5) + $signed(sext_ln225_fu_703_p1));

assign and_ln143_fu_365_p2 = (tmp_3_nbreadreq_fu_182_p3 & buffer_write_en);

assign and_ln215_fu_627_p2 = (xor_ln215_fu_621_p2 & ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state0 = ap_CS_iter2_fsm[32'd0];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_697 = (~((ap_done_reg == 1'b1) | (ap_start == 1'b0) | ((control_ch173_empty_n == 1'b0) & (tmp_nbreadreq_fu_174_p3 == 1'd1)) | ((ap_predicate_op116_read_state1 == 1'b1) & (vector_in_len_ch176_empty_n == 1'b0)) | ((stream_vector_in_TVALID_int_regslice == 1'b0) & (ap_predicate_op29_read_state1 == 1'b1)) | ((1'b1 == ap_CS_iter2_fsm_state3) & (((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & (((buffer_0_full_n == 1'b0) & (ap_predicate_op128_write_state2 == 1'b1)) | ((ap_predicate_op129_write_state2 == 1'b1) & (buffer_1_full_n == 1'b0))))) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_condition_744 = (~((ap_done_reg == 1'b1) | ((ap_predicate_op151_read_state3 == 1'b1) & (buffer_0_empty_n == 1'b0)) | ((ap_predicate_op144_read_state3 == 1'b1) & (buffer_1_empty_n == 1'b0)) | ((ap_predicate_op142_write_state3 == 1'b1) & (buffer_out_full_n == 1'b0))) & (1'b1 == ap_CS_iter2_fsm_state3) & (control_V_1_load_reg_964_pp0_iter1_reg == 8'd4) & (tmp_reg_960_pp0_iter1_reg == 1'd0));
end

assign ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_reg_327 = 'bx;

assign ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_reg_301 = 'bx;

assign ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_4_loc_0_reg_340 = 'bx;

assign ap_phi_reg_pp0_iter0_double_buffer_stream_stream_stream_stream_buffer_status_5_loc_reg_314 = 'bx;

assign ap_phi_reg_pp0_iter0_i_op_assign_1_reg_287 = 'bx;

assign ap_phi_reg_pp0_iter0_i_op_assign_2_reg_245 = 'bx;

assign ap_phi_reg_pp0_iter0_i_op_assign_3_reg_273 = 'bx;

assign ap_phi_reg_pp0_iter0_i_op_assign_reg_259 = 'bx;

always @ (*) begin
    ap_predicate_op116_read_state1 = ((tmp_s_nbreadreq_fu_196_p3 == 1'd1) & (control_V_1 == 8'd1) & (tmp_nbreadreq_fu_174_p3 == 1'd0));
end

always @ (*) begin
    ap_predicate_op128_write_state2 = ((control_V_1_load_reg_964 == 8'd4) & (tmp_reg_960 == 1'd0) & (1'd1 == and_ln143_reg_968) & (buffer_write_select_load_reg_991 == 1'd0));
end

always @ (*) begin
    ap_predicate_op129_write_state2 = ((control_V_1_load_reg_964 == 8'd4) & (tmp_reg_960 == 1'd0) & (1'd1 == and_ln143_reg_968) & (buffer_write_select_load_reg_991 == 1'd1));
end

always @ (*) begin
    ap_predicate_op142_write_state3 = ((buffer_data_read_valid_load_reg_972_pp0_iter1_reg == 1'd1) & (control_V_1_load_reg_964_pp0_iter1_reg == 8'd4) & (tmp_reg_960_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op144_read_state3 = ((buffer1_read_en_load_reg_1004_pp0_iter1_reg == 1'd1) & (buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd0) & (control_V_1_load_reg_964_pp0_iter1_reg == 8'd4) & (tmp_reg_960_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op151_read_state3 = ((buffer0_read_en_load_reg_1000_pp0_iter1_reg == 1'd1) & (control_V_1_load_reg_964_pp0_iter1_reg == 8'd4) & (tmp_reg_960_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op29_read_state1 = ((1'd1 == and_ln143_fu_365_p2) & (control_V_1 == 8'd4) & (tmp_nbreadreq_fu_174_p3 == 1'd0));
end

assign buffer0_read_en_load_load_fu_399_p1 = buffer0_read_en;

assign buffer1_read_en_load_load_fu_411_p1 = buffer1_read_en;

assign buffer_data_read_valid_load_load_fu_371_p1 = buffer_data_read_valid;

assign buffer_out_din = (or_ln147_8_fu_837_p7 | 21'd1);

assign buffer_write_select_load_load_fu_387_p1 = buffer_write_select;

assign icmp_ln1019_1_fu_477_p2 = ((double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4 == 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_431_p2 = ((double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5 == zext_ln1019_1_fu_427_p1) ? 1'b1 : 1'b0);

assign icmp_ln1019_3_fu_443_p2 = ((double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5 == 16'd1) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_465_p2 = ((double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4 == zext_ln1019_fu_461_p1) ? 1'b1 : 1'b0);

assign icmp_ln1031_1_fu_553_p2 = (($signed(double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5) < $signed(zext_ln1031_fu_493_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1031_fu_497_p2 = (($signed(double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4) < $signed(zext_ln1031_fu_493_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_1_fu_591_p2 = (($signed(tmp_210_fu_581_p4) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_535_p2 = (($signed(tmp_209_fu_525_p4) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign or_ln147_3_fu_767_p11 = {{{{{{{{{{buffer_data_read_data_V}, {15'd0}}, {buffer_data_read_pad_zero}}, {7'd0}}, {buffer_data_read_axis_last}}, {7'd0}}, {buffer_data_read_last_data_load_reg_981_pp0_iter1_reg}}, {7'd0}}, {buffer_data_read_first_data_load_reg_976_pp0_iter1_reg}}, {8'd0}};

assign or_ln147_8_fu_837_p7 = {{{{{{tmp_4_fu_827_p4}, {tmp_203_fu_819_p3}}, {tmp_202_fu_811_p3}}, {tmp_201_fu_803_p3}}, {tmp_200_fu_795_p3}}, {1'd0}};

assign or_ln147_fu_789_p2 = (or_ln147_3_fu_767_p11 | 64'd1);

assign or_ln214_fu_609_p2 = (ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 | ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_2_loc_0_phi_fu_330_p6);

assign p_s_fu_743_p5 = {{{{stream_data_v_data_V_reg_986}, {1'd0}}, {tmp_204_reg_995}}, {3'd0}};

assign select_ln1496_1_fu_689_p3 = ((ap_phi_mux_i_op_assign_3_phi_fu_276_p6[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln1496_fu_655_p3 = ((ap_phi_mux_i_op_assign_1_phi_fu_290_p6[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign sext_ln223_fu_669_p1 = $signed(add_ln1496_fu_663_p2);

assign sext_ln225_fu_703_p1 = $signed(add_ln1496_1_fu_697_p2);

assign stream_data_v_data_V_fu_383_p1 = stream_vector_in_TDATA_int_regslice[15:0];

assign stream_vector_in_TREADY = regslice_both_stream_vector_in_U_ack_in;

assign tmp_200_fu_795_p3 = or_ln147_fu_789_p2[64'd8];

assign tmp_201_fu_803_p3 = or_ln147_fu_789_p2[64'd16];

assign tmp_202_fu_811_p3 = or_ln147_fu_789_p2[64'd24];

assign tmp_203_fu_819_p3 = or_ln147_fu_789_p2[64'd32];

assign tmp_209_fu_525_p4 = {{double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_4[15:1]}};

assign tmp_210_fu_581_p4 = {{double_buffer_stream_stream_stream_stream_buffer_data_t_0_buffer_status_5[15:1]}};

assign tmp_3_nbreadreq_fu_182_p3 = stream_vector_in_TVALID_int_regslice;

assign tmp_4_fu_827_p4 = {{or_ln147_fu_789_p2[63:48]}};

assign tmp_nbreadreq_fu_174_p3 = control_ch173_empty_n;

assign tmp_s_nbreadreq_fu_196_p3 = vector_in_len_ch176_empty_n;

assign xor_ln215_fu_621_p2 = (ap_phi_mux_double_buffer_stream_stream_stream_stream_buffer_status_3_loc_phi_fu_304_p6 ^ 1'd1);

assign zext_ln1019_1_fu_427_p1 = vector_in_length_V_1;

assign zext_ln1019_fu_461_p1 = vector_in_length_V_1;

assign zext_ln1031_fu_493_p1 = vector_in_length_minus_1_V;

assign zext_ln1627_1_fu_685_p1 = ap_phi_mux_i_op_assign_2_phi_fu_248_p6;

assign zext_ln1627_fu_651_p1 = ap_phi_mux_i_op_assign_phi_fu_262_p6;

endmodule //RBM_double_buffer
