-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity RBM_sigmoid is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    systolic_out_dout : IN STD_LOGIC_VECTOR (48 downto 0);
    systolic_out_num_data_valid : IN STD_LOGIC_VECTOR (7 downto 0);
    systolic_out_fifo_cap : IN STD_LOGIC_VECTOR (7 downto 0);
    systolic_out_empty_n : IN STD_LOGIC;
    systolic_out_read : OUT STD_LOGIC;
    stream_sigmoid_switch_TVALID : IN STD_LOGIC;
    stream_vector_out_TREADY : IN STD_LOGIC;
    stream_sigmoid_switch_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_sigmoid_switch_TREADY : OUT STD_LOGIC;
    stream_vector_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    stream_vector_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of RBM_sigmoid is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter2_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter3_fsm_state4 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter4_fsm_state5 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter5_fsm_state6 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter6_fsm_state7 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter2_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter3_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter4_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter5_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_iter6_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv74_3FFFFFFFFFFFFFC0001 : STD_LOGIC_VECTOR (73 downto 0) := "11111111111111111111111111111111111111111111111111111111000000000000000001";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv47_100000 : STD_LOGIC_VECTOR (46 downto 0) := "00000000000000000000000000100000000000000000000";
    constant ap_const_lv48_100000 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000100000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter2_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter3_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter3_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter4_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter4_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter5_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter5_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter6_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter6_fsm_state0 : STD_LOGIC;
    signal tmp_nbreadreq_fu_98_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_nbreadreq_fu_106_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op16_read_state1 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_CS_iter2_fsm_state3 : STD_LOGIC;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_CS_iter3_fsm_state4 : STD_LOGIC;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_CS_iter4_fsm_state5 : STD_LOGIC;
    signal tmp_reg_404 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_404_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op66_write_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_CS_iter5_fsm_state6 : STD_LOGIC;
    signal tmp_reg_404_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op67_write_state7 : BOOLEAN;
    signal regslice_both_stream_vector_out_U_apdone_blk : STD_LOGIC;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_CS_iter6_fsm_state7 : STD_LOGIC;
    signal sigmoid_switch_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal sigmoid_slope_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal sigmoid_slope_V_ce0 : STD_LOGIC;
    signal sigmoid_slope_V_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal sigmoid_bias_V_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal sigmoid_bias_V_ce0 : STD_LOGIC;
    signal sigmoid_bias_V_q0 : STD_LOGIC_VECTOR (25 downto 0);
    signal stream_sigmoid_switch_TDATA_blk_n : STD_LOGIC;
    signal systolic_out_blk_n : STD_LOGIC;
    signal stream_vector_out_TDATA_blk_n : STD_LOGIC;
    signal tmp_reg_404_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_404_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_404_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_404_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_408_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal systolic_out_data_V_1_fu_159_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_data_V_1_reg_412 : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_data_V_1_reg_412_pp0_iter1_reg : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_data_V_1_reg_412_pp0_iter2_reg : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_data_V_1_reg_412_pp0_iter3_reg : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_data_V_1_reg_412_pp0_iter4_reg : STD_LOGIC_VECTOR (47 downto 0);
    signal systolic_out_axis_last_1_reg_418 : STD_LOGIC_VECTOR (0 downto 0);
    signal systolic_out_axis_last_1_reg_418_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal systolic_out_axis_last_1_reg_418_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal systolic_out_axis_last_1_reg_418_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal systolic_out_axis_last_1_reg_418_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_198_reg_423 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_198_reg_423_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_198_reg_423_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_198_reg_423_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_198_reg_423_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sigmoid_temp_V_fu_179_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal sigmoid_temp_V_reg_429 : STD_LOGIC_VECTOR (47 downto 0);
    signal icmp_ln610_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_reg_434 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_reg_434_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_reg_434_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln610_reg_434_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_132_fu_300_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal ret_V_132_reg_439 : STD_LOGIC_VECTOR (54 downto 0);
    signal ret_V_132_reg_439_pp0_iter2_reg : STD_LOGIC_VECTOR (54 downto 0);
    signal icmp_ln1019_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_454 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_454_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_454_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_454_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sigmoid_slope_V_load_reg_459 : STD_LOGIC_VECTOR (23 downto 0);
    signal rhs_67_reg_464 : STD_LOGIC_VECTOR (25 downto 0);
    signal rhs_67_reg_464_pp0_iter3_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal rhs_67_reg_464_pp0_iter4_reg : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_328_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal r_V_192_reg_479 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln613_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sigmoid_temp_V_2_fu_191_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal t_fu_196_p3 : STD_LOGIC_VECTOR (73 downto 0);
    signal trunc_ln1003_fu_220_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_fu_224_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal trunc_ln_fu_204_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1003_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_238_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1002_fu_244_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ret_V_131_fu_252_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_199_fu_260_p4 : STD_LOGIC_VECTOR (19 downto 0);
    signal lhs_130_fu_284_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal r_V_193_fu_276_p3 : STD_LOGIC_VECTOR (49 downto 0);
    signal sext_ln1348_fu_292_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal sext_ln1348_1_fu_296_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal grp_fu_328_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal rhs_68_fu_334_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal zext_ln1347_fu_341_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal ret_V_130_fu_345_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal sigmoid_out_data_V_fu_350_p4 : STD_LOGIC_VECTOR (46 downto 0);
    signal sigmoid_out_data_V_1_fu_360_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal sext_ln596_fu_367_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sigmoid_out_data_V_2_fu_371_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal sigmoid_out_data_V_3_fu_377_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal select_ln623_fu_384_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_2_fu_390_p4 : STD_LOGIC_VECTOR (64 downto 0);
    signal grp_fu_328_ce : STD_LOGIC;
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter2_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter3_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter4_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter5_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_iter6_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter2_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_iter3_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_iter4_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_iter5_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_iter6_fsm_state7_blk : STD_LOGIC;
    signal regslice_both_stream_sigmoid_switch_U_apdone_blk : STD_LOGIC;
    signal stream_sigmoid_switch_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal stream_sigmoid_switch_TVALID_int_regslice : STD_LOGIC;
    signal stream_sigmoid_switch_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_sigmoid_switch_U_ack_in : STD_LOGIC;
    signal stream_vector_out_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal stream_vector_out_TVALID_int_regslice : STD_LOGIC;
    signal stream_vector_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_stream_vector_out_U_vld_out : STD_LOGIC;
    signal grp_fu_328_p10 : STD_LOGIC_VECTOR (78 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component RBM_mul_55s_24ns_79_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (54 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (78 downto 0) );
    end component;


    component RBM_sigmoid_sigmoid_slope_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component RBM_sigmoid_sigmoid_bias_V_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component RBM_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    sigmoid_slope_V_U : component RBM_sigmoid_sigmoid_slope_V_ROM_AUTO_1R
    generic map (
        DataWidth => 24,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_slope_V_address0,
        ce0 => sigmoid_slope_V_ce0,
        q0 => sigmoid_slope_V_q0);

    sigmoid_bias_V_U : component RBM_sigmoid_sigmoid_bias_V_ROM_AUTO_1R
    generic map (
        DataWidth => 26,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => sigmoid_bias_V_address0,
        ce0 => sigmoid_bias_V_ce0,
        q0 => sigmoid_bias_V_q0);

    mul_55s_24ns_79_2_1_U117 : component RBM_mul_55s_24ns_79_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 55,
        din1_WIDTH => 24,
        dout_WIDTH => 79)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ret_V_132_reg_439_pp0_iter2_reg,
        din1 => grp_fu_328_p1,
        ce => grp_fu_328_ce,
        dout => grp_fu_328_p2);

    regslice_both_stream_sigmoid_switch_U : component RBM_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => stream_sigmoid_switch_TDATA,
        vld_in => stream_sigmoid_switch_TVALID,
        ack_in => regslice_both_stream_sigmoid_switch_U_ack_in,
        data_out => stream_sigmoid_switch_TDATA_int_regslice,
        vld_out => stream_sigmoid_switch_TVALID_int_regslice,
        ack_out => stream_sigmoid_switch_TREADY_int_regslice,
        apdone_blk => regslice_both_stream_sigmoid_switch_U_apdone_blk);

    regslice_both_stream_vector_out_U : component RBM_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => stream_vector_out_TDATA_int_regslice,
        vld_in => stream_vector_out_TVALID_int_regslice,
        ack_in => stream_vector_out_TREADY_int_regslice,
        data_out => stream_vector_out_TDATA,
        vld_out => regslice_both_stream_vector_out_U_vld_out,
        ack_out => stream_vector_out_TREADY,
        apdone_blk => regslice_both_stream_vector_out_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter2_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
            else
                ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter3_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
            else
                ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter4_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
            else
                ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter5_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
            else
                ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter6_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter6_fsm <= ap_ST_iter6_fsm_state0;
            else
                ap_CS_iter6_fsm <= ap_NS_iter6_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_iter6_fsm_state7))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2) and (tmp_s_reg_408_pp0_iter0_reg = ap_const_lv1_1) and (tmp_reg_404_pp0_iter0_reg = ap_const_lv1_0))) then
                icmp_ln1019_reg_454 <= icmp_ln1019_fu_316_p2;
                icmp_ln610_reg_434 <= icmp_ln610_fu_270_p2;
                    ret_V_132_reg_439(54 downto 6) <= ret_V_132_fu_300_p2(54 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                icmp_ln1019_reg_454_pp0_iter2_reg <= icmp_ln1019_reg_454;
                icmp_ln610_reg_434_pp0_iter2_reg <= icmp_ln610_reg_434;
                    ret_V_132_reg_439_pp0_iter2_reg(54 downto 6) <= ret_V_132_reg_439(54 downto 6);
                systolic_out_axis_last_1_reg_418_pp0_iter2_reg <= systolic_out_axis_last_1_reg_418_pp0_iter1_reg;
                systolic_out_data_V_1_reg_412_pp0_iter2_reg <= systolic_out_data_V_1_reg_412_pp0_iter1_reg;
                tmp_198_reg_423_pp0_iter2_reg <= tmp_198_reg_423_pp0_iter1_reg;
                tmp_reg_404_pp0_iter2_reg <= tmp_reg_404_pp0_iter1_reg;
                tmp_s_reg_408_pp0_iter2_reg <= tmp_s_reg_408_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                icmp_ln1019_reg_454_pp0_iter3_reg <= icmp_ln1019_reg_454_pp0_iter2_reg;
                icmp_ln610_reg_434_pp0_iter3_reg <= icmp_ln610_reg_434_pp0_iter2_reg;
                rhs_67_reg_464_pp0_iter3_reg <= rhs_67_reg_464;
                systolic_out_axis_last_1_reg_418_pp0_iter3_reg <= systolic_out_axis_last_1_reg_418_pp0_iter2_reg;
                systolic_out_data_V_1_reg_412_pp0_iter3_reg <= systolic_out_data_V_1_reg_412_pp0_iter2_reg;
                tmp_198_reg_423_pp0_iter3_reg <= tmp_198_reg_423_pp0_iter2_reg;
                tmp_reg_404_pp0_iter3_reg <= tmp_reg_404_pp0_iter2_reg;
                tmp_s_reg_408_pp0_iter3_reg <= tmp_s_reg_408_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                icmp_ln1019_reg_454_pp0_iter4_reg <= icmp_ln1019_reg_454_pp0_iter3_reg;
                icmp_ln610_reg_434_pp0_iter4_reg <= icmp_ln610_reg_434_pp0_iter3_reg;
                rhs_67_reg_464_pp0_iter4_reg <= rhs_67_reg_464_pp0_iter3_reg;
                systolic_out_axis_last_1_reg_418_pp0_iter4_reg <= systolic_out_axis_last_1_reg_418_pp0_iter3_reg;
                systolic_out_data_V_1_reg_412_pp0_iter4_reg <= systolic_out_data_V_1_reg_412_pp0_iter3_reg;
                tmp_198_reg_423_pp0_iter4_reg <= tmp_198_reg_423_pp0_iter3_reg;
                tmp_reg_404_pp0_iter4_reg <= tmp_reg_404_pp0_iter3_reg;
                tmp_s_reg_408_pp0_iter4_reg <= tmp_s_reg_408_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5) and (icmp_ln1019_reg_454_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln610_reg_434_pp0_iter3_reg = ap_const_lv1_0) and (tmp_s_reg_408_pp0_iter3_reg = ap_const_lv1_1) and (tmp_reg_404_pp0_iter3_reg = ap_const_lv1_0))) then
                r_V_192_reg_479 <= grp_fu_328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3) and (tmp_s_reg_408_pp0_iter1_reg = ap_const_lv1_1) and (tmp_reg_404_pp0_iter1_reg = ap_const_lv1_0))) then
                rhs_67_reg_464 <= sigmoid_bias_V_q0;
                sigmoid_slope_V_load_reg_459 <= sigmoid_slope_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                sigmoid_switch_V <= stream_sigmoid_switch_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (tmp_s_nbreadreq_fu_106_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                sigmoid_temp_V_reg_429 <= sigmoid_temp_V_fu_179_p2;
                systolic_out_axis_last_1_reg_418 <= systolic_out_dout(48 downto 48);
                systolic_out_data_V_1_reg_412 <= systolic_out_data_V_1_fu_159_p1;
                tmp_198_reg_423 <= systolic_out_dout(47 downto 47);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                systolic_out_axis_last_1_reg_418_pp0_iter1_reg <= systolic_out_axis_last_1_reg_418;
                systolic_out_data_V_1_reg_412_pp0_iter1_reg <= systolic_out_data_V_1_reg_412;
                tmp_198_reg_423_pp0_iter1_reg <= tmp_198_reg_423;
                tmp_reg_404_pp0_iter1_reg <= tmp_reg_404;
                tmp_s_reg_408_pp0_iter1_reg <= tmp_s_reg_408;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                tmp_reg_404 <= tmp_nbreadreq_fu_98_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                tmp_reg_404_pp0_iter5_reg <= tmp_reg_404_pp0_iter4_reg;
                tmp_s_reg_408_pp0_iter5_reg <= tmp_s_reg_408_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                tmp_s_reg_408 <= tmp_s_nbreadreq_fu_106_p3;
            end if;
        end if;
    end process;
    ret_V_132_reg_439(5 downto 0) <= "000000";
    ret_V_132_reg_439_pp0_iter2_reg(5 downto 0) <= "000000";

    ap_NS_iter0_fsm_assign_proc : process (ap_start, ap_CS_iter0_fsm, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_sigmoid_switch_TVALID_int_regslice, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_sigmoid_switch_TVALID_int_regslice, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state1) and ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0))))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter2_fsm_assign_proc : process (ap_CS_iter2_fsm, ap_done_reg, ap_CS_iter1_fsm_state2, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter2_fsm is
            when ap_ST_iter2_fsm_state3 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_0 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                end if;
            when ap_ST_iter2_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state3;
                else
                    ap_NS_iter2_fsm <= ap_ST_iter2_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter2_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter3_fsm_assign_proc : process (ap_CS_iter3_fsm, ap_done_reg, ap_CS_iter2_fsm_state3, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter3_fsm is
            when ap_ST_iter3_fsm_state4 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_0 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state0;
                else
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                end if;
            when ap_ST_iter3_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter2_fsm_state3))) then
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state4;
                else
                    ap_NS_iter3_fsm <= ap_ST_iter3_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter3_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter4_fsm_assign_proc : process (ap_CS_iter4_fsm, ap_done_reg, ap_CS_iter3_fsm_state4, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter4_fsm is
            when ap_ST_iter4_fsm_state5 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_0 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state0;
                else
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                end if;
            when ap_ST_iter4_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4))) then
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state5;
                else
                    ap_NS_iter4_fsm <= ap_ST_iter4_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter4_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter5_fsm_assign_proc : process (ap_CS_iter5_fsm, ap_done_reg, ap_CS_iter4_fsm_state5, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter5_fsm is
            when ap_ST_iter5_fsm_state6 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))))) and (ap_const_logic_0 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state0;
                else
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                end if;
            when ap_ST_iter5_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5))) then
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state6;
                else
                    ap_NS_iter5_fsm <= ap_ST_iter5_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter5_fsm <= "XX";
        end case;
    end process;

    ap_NS_iter6_fsm_assign_proc : process (ap_CS_iter6_fsm, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        case ap_CS_iter6_fsm is
            when ap_ST_iter6_fsm_state7 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) and not(((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) and ((ap_const_logic_0 = ap_CS_iter5_fsm_state6) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1))))))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state0;
                else
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                end if;
            when ap_ST_iter6_fsm_state0 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6))) then
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state7;
                else
                    ap_NS_iter6_fsm <= ap_ST_iter6_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter6_fsm <= "XX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);
    ap_CS_iter2_fsm_state0 <= ap_CS_iter2_fsm(0);
    ap_CS_iter2_fsm_state3 <= ap_CS_iter2_fsm(1);
    ap_CS_iter3_fsm_state0 <= ap_CS_iter3_fsm(0);
    ap_CS_iter3_fsm_state4 <= ap_CS_iter3_fsm(1);
    ap_CS_iter4_fsm_state0 <= ap_CS_iter4_fsm(0);
    ap_CS_iter4_fsm_state5 <= ap_CS_iter4_fsm(1);
    ap_CS_iter5_fsm_state0 <= ap_CS_iter5_fsm(0);
    ap_CS_iter5_fsm_state6 <= ap_CS_iter5_fsm(1);
    ap_CS_iter6_fsm_state0 <= ap_CS_iter6_fsm(0);
    ap_CS_iter6_fsm_state7 <= ap_CS_iter6_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_start, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, stream_sigmoid_switch_TVALID_int_regslice)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)))) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_iter2_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_iter3_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_iter4_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_iter5_fsm_state6_blk_assign_proc : process(ap_predicate_op66_write_state6, ap_block_state6_io, stream_vector_out_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))) then 
            ap_ST_iter5_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_iter5_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter6_fsm_state7_blk_assign_proc : process(ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, stream_vector_out_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) then 
            ap_ST_iter6_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_iter6_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, stream_sigmoid_switch_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)));
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(ap_predicate_op66_write_state6, stream_vector_out_TREADY_int_regslice)
    begin
                ap_block_state6_io <= ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage0_iter5_assign_proc : process(ap_predicate_op66_write_state6, stream_vector_out_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter5 <= ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_io_assign_proc : process(ap_predicate_op67_write_state7, stream_vector_out_TREADY_int_regslice)
    begin
                ap_block_state7_io <= ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage0_iter6_assign_proc : process(ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, stream_vector_out_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage0_iter6 <= ((regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_iter6_fsm_state7))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0, ap_CS_iter2_fsm_state0, ap_CS_iter3_fsm_state0, ap_CS_iter4_fsm_state0, ap_CS_iter5_fsm_state0, ap_CS_iter6_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter6_fsm_state0) and (ap_const_logic_1 = ap_CS_iter5_fsm_state0) and (ap_const_logic_1 = ap_CS_iter4_fsm_state0) and (ap_const_logic_1 = ap_CS_iter3_fsm_state0) and (ap_const_logic_1 = ap_CS_iter2_fsm_state0) and (ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op16_read_state1_assign_proc : process(tmp_nbreadreq_fu_98_p3, tmp_s_nbreadreq_fu_106_p3)
    begin
                ap_predicate_op16_read_state1 <= ((tmp_s_nbreadreq_fu_106_p3 = ap_const_lv1_1) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_0));
    end process;


    ap_predicate_op66_write_state6_assign_proc : process(tmp_reg_404_pp0_iter4_reg, tmp_s_reg_408_pp0_iter4_reg)
    begin
                ap_predicate_op66_write_state6 <= ((tmp_s_reg_408_pp0_iter4_reg = ap_const_lv1_1) and (tmp_reg_404_pp0_iter4_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op67_write_state7_assign_proc : process(tmp_reg_404_pp0_iter5_reg, tmp_s_reg_408_pp0_iter5_reg)
    begin
                ap_predicate_op67_write_state7 <= ((tmp_s_reg_408_pp0_iter5_reg = ap_const_lv1_1) and (tmp_reg_404_pp0_iter5_reg = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_sigmoid_switch_TVALID_int_regslice, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_328_ce_assign_proc : process(ap_done_reg, ap_CS_iter3_fsm_state4, ap_CS_iter4_fsm_state5, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if (((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter4_fsm_state5)) or (not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter3_fsm_state4)))) then 
            grp_fu_328_ce <= ap_const_logic_1;
        else 
            grp_fu_328_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_328_p1 <= grp_fu_328_p10(24 - 1 downto 0);
    grp_fu_328_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sigmoid_slope_V_load_reg_459),79));
    icmp_ln1003_fu_232_p2 <= "1" when (tmp_1_fu_224_p3 = ap_const_lv20_0) else "0";
    icmp_ln1019_fu_316_p2 <= "1" when (sigmoid_switch_V = ap_const_lv8_0) else "0";
    icmp_ln610_fu_270_p2 <= "1" when (signed(tmp_199_fu_260_p4) > signed(ap_const_lv20_0)) else "0";
    lhs_130_fu_284_p3 <= (sigmoid_temp_V_2_fu_191_p3 & ap_const_lv6_0);
    p_Result_s_fu_214_p2 <= "1" when (signed(t_fu_196_p3) < signed(ap_const_lv74_3FFFFFFFFFFFFFC0001)) else "0";
    r_V_193_fu_276_p3 <= (ret_V_131_fu_252_p3 & ap_const_lv18_0);
    ret_V_130_fu_345_p2 <= std_logic_vector(unsigned(r_V_192_reg_479) + unsigned(zext_ln1347_fu_341_p1));
    ret_V_131_fu_252_p3 <= 
        select_ln1002_fu_244_p3 when (p_Result_s_fu_214_p2(0) = '1') else 
        trunc_ln_fu_204_p4;
    ret_V_132_fu_300_p2 <= std_logic_vector(signed(sext_ln1348_fu_292_p1) - signed(sext_ln1348_1_fu_296_p1));
    ret_V_fu_238_p2 <= std_logic_vector(unsigned(trunc_ln_fu_204_p4) + unsigned(ap_const_lv32_1));
    rhs_68_fu_334_p3 <= (rhs_67_reg_464_pp0_iter4_reg & ap_const_lv26_0);
    select_ln1002_fu_244_p3 <= 
        trunc_ln_fu_204_p4 when (icmp_ln1003_fu_232_p2(0) = '1') else 
        ret_V_fu_238_p2;
    select_ln623_fu_384_p3 <= 
        systolic_out_data_V_1_reg_412_pp0_iter4_reg when (icmp_ln1019_reg_454_pp0_iter4_reg(0) = '1') else 
        sigmoid_out_data_V_3_fu_377_p3;
        sext_ln1348_1_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_193_fu_276_p3),55));

        sext_ln1348_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(lhs_130_fu_284_p3),55));

        sext_ln596_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sigmoid_out_data_V_1_fu_360_p3),48));

    sigmoid_bias_V_address0 <= zext_ln613_fu_306_p1(12 - 1 downto 0);

    sigmoid_bias_V_ce0_assign_proc : process(ap_done_reg, ap_CS_iter1_fsm_state2, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            sigmoid_bias_V_ce0 <= ap_const_logic_1;
        else 
            sigmoid_bias_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sigmoid_out_data_V_1_fu_360_p3 <= 
        ap_const_lv47_100000 when (icmp_ln610_reg_434_pp0_iter4_reg(0) = '1') else 
        sigmoid_out_data_V_fu_350_p4;
    sigmoid_out_data_V_2_fu_371_p2 <= std_logic_vector(unsigned(ap_const_lv48_100000) - unsigned(sext_ln596_fu_367_p1));
    sigmoid_out_data_V_3_fu_377_p3 <= 
        sigmoid_out_data_V_2_fu_371_p2 when (tmp_198_reg_423_pp0_iter4_reg(0) = '1') else 
        sext_ln596_fu_367_p1;
    sigmoid_out_data_V_fu_350_p4 <= ret_V_130_fu_345_p2(78 downto 32);
    sigmoid_slope_V_address0 <= zext_ln613_fu_306_p1(12 - 1 downto 0);

    sigmoid_slope_V_ce0_assign_proc : process(ap_done_reg, ap_CS_iter1_fsm_state2, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2))) then 
            sigmoid_slope_V_ce0 <= ap_const_logic_1;
        else 
            sigmoid_slope_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    sigmoid_temp_V_2_fu_191_p3 <= 
        sigmoid_temp_V_reg_429 when (tmp_198_reg_423(0) = '1') else 
        systolic_out_data_V_1_reg_412;
    sigmoid_temp_V_fu_179_p2 <= std_logic_vector(unsigned(ap_const_lv48_0) - unsigned(systolic_out_data_V_1_fu_159_p1));

    stream_sigmoid_switch_TDATA_blk_n_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, tmp_nbreadreq_fu_98_p3, ap_done_reg, stream_sigmoid_switch_TVALID_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            stream_sigmoid_switch_TDATA_blk_n <= stream_sigmoid_switch_TVALID_int_regslice;
        else 
            stream_sigmoid_switch_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_sigmoid_switch_TREADY <= regslice_both_stream_sigmoid_switch_U_ack_in;

    stream_sigmoid_switch_TREADY_int_regslice_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_sigmoid_switch_TVALID_int_regslice, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            stream_sigmoid_switch_TREADY_int_regslice <= ap_const_logic_1;
        else 
            stream_sigmoid_switch_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    stream_vector_out_TDATA_blk_n_assign_proc : process(ap_predicate_op66_write_state6, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))) then 
            stream_vector_out_TDATA_blk_n <= stream_vector_out_TREADY_int_regslice;
        else 
            stream_vector_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_vector_out_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_390_p4),128));
    stream_vector_out_TVALID <= regslice_both_stream_vector_out_U_vld_out;

    stream_vector_out_TVALID_int_regslice_assign_proc : process(ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))))) and (ap_const_logic_1 = ap_CS_iter5_fsm_state6) and (ap_predicate_op66_write_state6 = ap_const_boolean_1))) then 
            stream_vector_out_TVALID_int_regslice <= ap_const_logic_1;
        else 
            stream_vector_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    systolic_out_blk_n_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, systolic_out_empty_n, ap_predicate_op16_read_state1, ap_done_reg)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_predicate_op16_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            systolic_out_blk_n <= systolic_out_empty_n;
        else 
            systolic_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    systolic_out_data_V_1_fu_159_p1 <= systolic_out_dout(48 - 1 downto 0);

    systolic_out_read_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, systolic_out_empty_n, tmp_nbreadreq_fu_98_p3, ap_predicate_op16_read_state1, ap_done_reg, ap_predicate_op66_write_state6, ap_block_state6_io, ap_CS_iter5_fsm_state6, ap_predicate_op67_write_state7, regslice_both_stream_vector_out_U_apdone_blk, ap_block_state7_io, ap_CS_iter6_fsm_state7, stream_sigmoid_switch_TVALID_int_regslice, stream_vector_out_TREADY_int_regslice)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0) or ((tmp_nbreadreq_fu_98_p3 = ap_const_lv1_1) and (stream_sigmoid_switch_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op16_read_state1 = ap_const_boolean_1) and (systolic_out_empty_n = ap_const_logic_0)) or ((ap_const_logic_1 = ap_CS_iter6_fsm_state7) and ((ap_const_boolean_1 = ap_block_state7_io) or (regslice_both_stream_vector_out_U_apdone_blk = ap_const_logic_1) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op67_write_state7 = ap_const_boolean_1)))) or ((ap_const_logic_1 = ap_CS_iter5_fsm_state6) and ((ap_const_boolean_1 = ap_block_state6_io) or ((stream_vector_out_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op66_write_state6 = ap_const_boolean_1)))))) and (ap_predicate_op16_read_state1 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            systolic_out_read <= ap_const_logic_1;
        else 
            systolic_out_read <= ap_const_logic_0;
        end if; 
    end process;

    t_fu_196_p3 <= (sigmoid_temp_V_2_fu_191_p3 & ap_const_lv26_0);
    tmp_199_fu_260_p4 <= ret_V_131_fu_252_p3(31 downto 12);
    tmp_1_fu_224_p3 <= (trunc_ln1003_fu_220_p1 & ap_const_lv8_0);
    tmp_2_fu_390_p4 <= ((systolic_out_axis_last_1_reg_418_pp0_iter4_reg & ap_const_lv16_0) & select_ln623_fu_384_p3);
    tmp_nbreadreq_fu_98_p3 <= (0=>(stream_sigmoid_switch_TVALID_int_regslice), others=>'-');
    tmp_reg_404_pp0_iter0_reg <= tmp_reg_404;
    tmp_s_nbreadreq_fu_106_p3 <= (0=>(systolic_out_empty_n), others=>'-');
    tmp_s_reg_408_pp0_iter0_reg <= tmp_s_reg_408;
    trunc_ln1003_fu_220_p1 <= sigmoid_temp_V_2_fu_191_p3(12 - 1 downto 0);
    trunc_ln_fu_204_p4 <= sigmoid_temp_V_2_fu_191_p3(43 downto 12);
    zext_ln1347_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_68_fu_334_p3),79));
    zext_ln613_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ret_V_131_fu_252_p3),64));
end behav;
